name: ESP-IDF CI
on: [push]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        idf:
            - v6.0
            - v5.5
        example:
            - gauge-cal
        target:
            - esp32
            - esp32c6
    container:
      image: espressif/idf:release-${{ matrix.idf }}
      options: -u 2025:2025
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v5
        with:
          path: |
            ${{ github.workspace }}/.cache/ccache
          key: idf-${{ matrix.idf }}-${{ matrix.target }}-${{ matrix.example }}
      - name: Build ${{ matrix.example }} on ${{ matrix.target }}
        shell: bash
        run: |
            source /opt/esp/idf/export.sh
            cd examples/${{ matrix.example }}
            idf.py build
            ccache -s
        env:
          IDF_TARGET: ${{ matrix.target }}
          IDF_CCACHE_ENABLE: "1"
          CCACHE_DIR: ${{ github.workspace }}/.cache/ccache
