name: ESP-IDF CI
on:
  push:
    paths:
      - '.github/workflows/esp-idf.yaml'
      - 'examples/**'
      - 'src/**'
  pull_request:
    paths:
      - '.github/workflows/esp-idf.yaml'
      - 'examples/**'
      - 'src/**'

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        idf:
            - v6.0
            - v5.5
        example:
            - gauge-cal
            - move-test
            - move-test-threads
        target:
            - esp32
            - esp32c6
    container:
      image: espressif/idf:release-${{ matrix.idf }}
      options: -u 2025:2025
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v5
        with:
          path: |
            ${{ github.workspace }}/.cache/ccache
          key: idf-${{ matrix.idf }}-${{ matrix.target }}-${{ matrix.example }}
      - name: Build ${{ matrix.example }} on ${{ matrix.target }}
        shell: bash
        run: |
            source /opt/esp/idf/export.sh
            cd examples/${{ matrix.example }}
            idf.py build
            ccache -s
        env:
          IDF_TARGET: ${{ matrix.target }}
          IDF_CCACHE_ENABLE: "1"
          CCACHE_DIR: ${{ github.workspace }}/.cache/ccache
          TERM: xterm-256color
          CLICOLOR_FORCE: "1"
          FORCE_COLOR: "1"
          PY_COLORS: "1"
          CMAKE_COLOR_DIAGNOSTICS: "ON"
