name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-release:
    runs-on: self-hosted
    container:
      image: ghcr.io/petrows/platformio:v4
      options: -u 2025:2025
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          draft: true
          generate_release_notes: true
